### ISSUE TITLE
Safari: clicking a paper-icon-button in a list that doesn't start at the top makes it jump

### ISSUE THREAD

**Issue by notwaldorf** [PolymerElements/iron-list#329]
Repro steps: http://output.jsbin.com/pixuhac
Scroll down for a bit, then click on the first item's paper-icon-button. The list jumps up.

**Comment by blasten** [comment]
You can fix the issue by adding a `padding-top` to `#list` so that the list knows about the content above.

```css
#list {
  padding-top: 400px;
  margin-top: -400px;
}
```
